### ISSUE TITLE
Adult content on user feed is not hidden

### ISSUE THREAD

**Issue by Thallassa** [Nexus-Mods/web-issues#105]
So on ousnius's profile there is of course an endless stream of boobs https://rd.nexusmods.com/fallout4/users/4291759?tab=about+me

The problem is the boobs are showing up even when I have "don't show adult content' checked in my preferences. I know that the check is all synced properly because when I click to actually go to CBBE it tells me I've blocked adult content and I can't see the mod, but ousnius's page is still naked boobs everywhere.

**Comment by verenion** [comment]
Assigned PT#151593824

**Comment by Quintuplin** [comment]
I'd like to supplement to this that, even with 'show adult content' on, I don't think boobs should be flying around on the front page, or as a mod's primary thumbnail. 

I like to browse and install mods in varied environments, and just because I'm making my game NSFW doesn't mean my web browsing needs to be as well. At very least having a 'hide NSFW thumbnails' option, as a separate setting from 'hide NSFW mods', would be a great way to solve this issue.

**Comment by iamtiz** [comment]
Fixed
