### ISSUE TITLE
Download Flow, Download button update broken

### ISSUE THREAD

**Issue by sockko** [Nexus-Mods/web-issues#1065]
After you updated what happens when someone tries to download a mod I've noticed the following things:
1) the site as a whole feels cheaper since it gives constant reminders of premium download speeds.
2) the actual download (both manual and vortex) no longer work.
Another bug i noticed (before whatever update you pushed between my download clicks) was some images on mods failing to load.
long story short anyone who experiences these same issues will most likely search for a new mod site like i will be doing. 
You took something that worked . . . and broke it.

**Comment by Reeckensall** [comment]
Also unable to download anything since this update hit. Was downloading mods fine just before the update hit for me and then immediately became unable to download using the mod manager option. Manual still works for me, but all download manager downloads fail with the "click here to download manually" text generating dead links that always end in the following: 

&nmm=1#ERROR-download-location-not-found

**Comment by SundialPaisley** [comment]
Oh god, I am so flippin' glad I am not the only one! This covert update sorta screwed up the download links! I use MO2 and "Mod Manager Download" just won't work! After the whole "Slow download/Fast Download" it tells me that my mod has started downloading, but it doesn't!

**Comment by MonkeyManTV** [comment]
Same. I got on a little while ago to get a couple new meme mods for oblivion and i have to do everything manually i even tried skyrim and fallout 4 but i cant use the mod manager button at al the new layout broke my vortex button :(

**Comment by mrmason** [comment]
Thanks for reporting this, it should all be working correctly now.
