### ISSUE TITLE
Systematically have to signup twice to log-in !

### ISSUE THREAD

**Issue by zwazo** [Nexus-Mods/web-issues#1111]
## Bug/error being reported:
What's going on. Lately, every single time I sign-up, I'm redericted to the login form with the recaptcha ... and have to sing-up a second time before i'm allowed to acces the Nexus website.
I'm fed up !

I tried 
- different navigators : Firfox & Chrome
- different passwords : I changed the orders AND VALUE of the numbers and special chars i used in them
- different ways to fill-in : I tried by typing then copy-pasting those passwords
AND IT IS WERY SYSTEMATIC!

## Steps to reproduce:
1. Go to https://www.nexusmods.com/
2. accept the privacy splash-screen
3. click on log-in button on top of the page
4. fill-in login and password, and validate the form
5. refill it and click the recaptcha.

I will gladly help you by giving you more details, I actually recorded a footage to demonstrate it and give more clue here :  https://send.firefox.com/download/2bbe41fff0a83bfc/#BDoBmS0rqMTtn7-tBi02xg
(Will expire after 2 download or 7 days)

## Expected result:
To log-in on first attempt !

## Actual result:
I have to re sign and fill the recaptcha.
Note : I usually just have to click it once, but due to the many attemps while troobleshooting, I had to go to a more complex recaptcha (seen in the footage).

**Comment by verenion** [comment]
internal reference: [#171856718]

**Comment by zwazo** [comment]
I don't know if you've made anything, but I have to report that I can login again in one single step.
It works as attended again.

**Comment by Avrie05** [comment]
I'd like to add to this bug report, as it appears to be a timing issue with recaptcha, and turn it into a feature request. This issue is hit or miss. the recaptcha "I am not a robot" box comes up after logging in about one in three times "randomly" I don't believe anyone would have a problem with it if it was built directly into the sign in page when it loads. It's only a bug because it isn't there until you login. and as said not every time. It needs to load with the page "EVERY" time before you log in that first time and it wouldn't be an issue. 

I have to agree with @zwazo. it is getting annoying enough that I'm here as well. I'm getting sick of typing my credentials twice to log in ... please just make the damn button part of the page not an after thought.

**Comment by verenion** [comment]
We made a change yesterday that should have fixed the original issue above.

@Avrie05 The recaptcha is built into the page. The issue here is that it wasn't loading correctly on the first page load, meaning that every login would fail the first time. That should now be fixed. You won't however see it every single time - as google's recaptcha take multiple things into account to protect against automated signups.

**Comment by zwazo** [comment]
Thanks.
