### ISSUE TITLE
New mods this week - sort by "last updated" not working

### ISSUE THREAD

**Issue by Dreifels** [Nexus-Mods/web-issues#1211]
New mods this week - sort by "last updated" not working
updated two mods but not sort in
Muehlenwasser Refugium (Millwater Retreat) 2.0 DV1.5 Last updated 26 September 2020 3:51PM 
Reitbare Kamele und Dromedare 4.4 DV Last updated 26 September 2020 2:15PM 
BTW: you need to reopen #1209 as problem expands

**Comment by Pickysaurus** [comment]
You have already seen and commented on the news post related to #1209 (I also see you've added a comment about an unrelated problem to that issue which has since been fixed). 

We are aware of various problems with mod sorting and hot files. These will likely be addressed during the week. Thanks for the report.

**Comment by Pickysaurus** [comment]
related to #1210

**Comment by Pickysaurus** [comment]
Please try again, this should be resolved.

**Comment by Dreifels** [comment]
New mods this week - last updated
ttps://www.nexusmods.com/skyrimspecialedition/mods/thisweek/?BH=0
complete missing: Identity Crisis-1-04 DV Last Update: 27 Sep 2020
OK: Der Sidrat - wohnen an jedem Ort 4.03 DV Last Update: 27 Sep 2020
OK: Der Sidrat - Unleashed (Fall der Dwemer) 4.03 DV Last Update: 27 Sep 2020

**Comment by Dreifels** [comment]
ok, seems to be fine now
