### ISSUE TITLE
I can't see the real endorsements for mods and images sometimes i can't see how mutch views i get.

### ISSUE THREAD

**Issue by godsp33d6** [Nexus-Mods/web-issues#1276]

**Comment by Pickysaurus** [comment]
Hi godsp33d6
Can you please provide more details on the issue you're having? If possible please include screenshots to illustrate your point.

**Comment by godsp33d6** [comment]
Hi sure.Before i open my mods page only checking the mods 
![image](https://user-images.githubusercontent.com/77836060/105504752-00432580-5c7d-11eb-99b4-99f0e08d2243.png)
After i click on mod it show real endorsements and views.
![image](https://user-images.githubusercontent.com/77836060/105504834-12bd5f00-5c7d-11eb-8463-d60e23f391cd.png)

**Comment by godsp33d6** [comment]
Every mod show the endorsements before like them freeze they didn't up abit.Then after i click on mods it show real endorsements and views weird.

**Comment by Pickysaurus** [comment]
So if I'm interpreting this correctly, you're seeing the mod preview in the search results is slightly behind the actual page in terms of endorsements? This is because the results are cached. It will usually update in around an hour. However, our team are looking at ways to make the results page more up to date without dramatically slowing the site down.

**Comment by godsp33d6** [comment]
For me didn't update from 125 endorsement from my mod and it took days  and now im 135 endorsements lol.

**Comment by Pickysaurus** [comment]
Closing in favour of a more detailed report https://github.com/Nexus-Mods/web-issues/issues/1279
