### ISSUE TITLE
Mods with available updates do not appear on the updated page.

### ISSUE THREAD

**Issue by Juanpa98ar** [Nexus-Mods/web-issues#1279]
## Bug/error being reported:
The page does not show updated mods 

## Steps to reproduce:

When you go to the stardew valley mods page, the updated mods are not shown, even if you go to the updated tab.

### Example:
1. Updated mods are not displayed
2. It is possible to see the updated mods on the first page with F5 (refresh), the rest of the pages are not.

## Expected result:
View updated mods, update available

## Actual result:
No updated mod is shown and I can't know its current status. Results displayed using F5, new mods appear, updated mods only appear on first page after F5.
![Captura de pantalla (52)](https://user-images.githubusercontent.com/75898594/105630844-0fb3a180-5e2a-11eb-96be-4f90dc21cb97.png)
![Captura de pantalla (53)](https://user-images.githubusercontent.com/75898594/105630850-13dfbf00-5e2a-11eb-941c-c6a96091a8a4.png)

**Comment by godsp33d6** [comment]
I can confirm this too also i did report this almost 2 days ago they didn't give me a answer lol.

**Comment by alfaz62** [comment]
Created an account to submit this as well. 

URL:
https://www.nexusmods.com/fallout4?tab=updated
Username on the Nexus: 
alfaz62
Bug/error being reported:
updated mods not shown, cached page sometime?

Steps to reproduce:
 when clicking "updated" tab, looking for sim settlements 2 and workshop frameworks most recent update, as well as much better 3rd person animations and FallUI Workbench, none show up even when scrolling back several days. Pressing "view more- updated mods" to go to page 2, then pressing the back arrow loads a cached page,  i was able to see much better 3rd person + Fallui Workbench. 

Expected result: 
When clicking view more, i should see the above mentioned mods 

Actual result: 
Several mods fail to ever appear in the updated section. i only realised the mods were updated because i follow the authors youtube channels, and by luck with the back button cache 

Link to the affected mod/image (if relevant): 
the following is page 3 of view more - updated. Nadie's SREP for reference was update that i saw.
 ![image](https://user-images.githubusercontent.com/77950426/105661211-c000c480-5e81-11eb-8efc-2288a1c160ab.png)

when i pressed back to return to the initial FO4 page, the updated mods tab looked like this
![image](https://user-images.githubusercontent.com/77950426/105660949-0e619380-5e81-11eb-992f-3a49b9df143a.png)

**Comment by alfaz62** [comment]
why was this closed? did this get resolved? i'm still seeing discrepancies
