### ISSUE TITLE
Mod Page Tabs - Mobile site

### ISSUE THREAD

**Issue by BunnyX53** [Nexus-Mods/web-issues#1306]
Mobile site, can't load images/posts/files tabs on mod pages. Can only access description

**Comment by Pickysaurus** [comment]
The "Tabs" section uses a standard dropdown box, however, some browser zoom or accessibility settings can cause problems with it.

**Comment by NoCrazyShet** [comment]
It happens regardless of browser and zoom. It was working before the weekend, but now the site won't change views after selection.

**Comment by BunnyX53** [comment]
Yeh I can't get it to work at all, tried different browsers. All I can look at is the mod descriptions

**Comment by NoCrazyShet** [comment]
> Yeh I can't get it to work at all, tried different browsers. All I can look at is the mod descriptions

Yeah I 2nd this. I've also tried on multiple different devices, same issue each time.

**Comment by Pickysaurus** [comment]
As a temporary fix, you can try "View Desktop site". 
I'm not able to replicate this issue using Chrome on Android.

**Comment by Pickysaurus** [comment]
Can you try again now? We found that some browser are not supporting the ?? operator in JavaScript so this was causing anything JS-related to fail.

**Comment by NoCrazyShet** [comment]
It seems like I am still not able to, I'm not sure the ?? Operator would be
the cause. I suspect it may be something zoom related, as you mentioned
earlier. It's just strange that it appeared a few weeks ago, but worked
perfectly prior to that.

**Comment by Pickysaurus** [comment]
Hmm, this could be related to the settings discussed in #746 then?

**Comment by NoCrazyShet** [comment]
I've tried the settings and it still doesn't work. Something with the responsive design of the nav bar seems to be out of sorts though and I suspect that may be causing the issue.

The top nav is a good 10% larger than the rest of the viewport, thus extending outside of the borders of the screen, unless scrolled. Or when zoomed negatively. The screenshot is zoomed all the way out to display the image. 

![Screenshot_20210306-172450_Chrome](https://user-images.githubusercontent.com/33088454/110213564-e7937580-7ea0-11eb-8dc7-e9ead2a6948a.jpg)

I suspect you were right all along and it has something to do with browser zoom, I just find it weird that the problem is so recent. I'm on a Samsung galaxy s20, if that helps tracking it.

**Comment by BunnyX53** [comment]
No mine still doesn't work unfortunately. Only in desktop mode

**Comment by Pickysaurus** [comment]
I've been able to replicate this problem. We are tracking it internally now. It only stopped working for me from this morning though.

**Comment by fac851** [comment]
I have this problem only when logged in, you could check if it's working ok after logging out.

**Comment by NoCrazyShet** [comment]
> I have this problem only when logged in, you could check if it's working ok after logging out.

I can confirm this, logging out and incognito browsing both reenable navigating between tabs.

**Comment by SSyl** [comment]
I was able to replicate this problem using my Android phone (OnePlus 6) as well as using Google Chrome on Windows 10 via the Developer Tools.

It only happens while logged into an account.

To replicate using Google Chrome on Windows, open the dev tools (F12), enable the device toolbar (Ctrl + Shift + M) and add an Android device to the device list. I chose Pixel 2, since that's a Google made device. Then refresh the page and try to navigate between description/files/images/etc.

This does not happen when using Firefox on Android. Seems exclusive to Google Chrome and only while logged in.

**Comment by SSyl** [comment]
I did some more testing and if you remove either the Share or Report Abuse button, it fixes the issue. Actually, even just removing the text "Share" or part of the words of "Report Abuse" fixes the issue as well... which is odd.

**Comment by Pickysaurus** [comment]
Wow, @SSyl thanks for going the extra mile! I'll make sure to add this to our internal ticket so the devs know what you've discovered.

**Comment by TastelessOne** [comment]
As of just now, I can verify the mobile site has issues  Chrome (Android, current versions of both OS and browser)

1) You can only view the description page of each mod.
2) If you switch to the desktop site, images are too big for the screen. This is odd, because my phone has a 1440x2560 screen and the game images are only 1080p. If there's another setting I need to change, that's just one more reason to fix the mobile site.

**Comment by Pickysaurus** [comment]
This issue should be resolved, thanks for being patient. 
Also closes #746
