### ISSUE TITLE
Vortex Mark as Light Bug

### ISSUE THREAD

**Issue by lucase5** [Nexus-Mods/web-issues#1350]
## Your username/username(s) affected
lucase5

## Bug/error being reported:
 Vortex mark SNIFF mod as light even though it requires FormID compacting according to SSEEdit

## Steps to reproduce:
 1. Install SNIFF via Vortex
2. Mark it as light via Vortex

## Expected result:
Normal gameplay

## Actual result:
CTDs after a few seconds

**Comment by Pickysaurus** [comment]
This is not likely to be an issue caused by Vortex itself. This bug tracker is also intended for issues with the Nexus Mods website. You can send feedback about the Vortex app as shown below:

![image](https://user-images.githubusercontent.com/31670524/116546904-1ef33100-a8ea-11eb-8cab-e57404dba710.png)
