### ISSUE TITLE
Despite Staff Insistence that Notifications are "Fixed," They Are Not

### ISSUE THREAD

**Issue by Vyxenne** [Nexus-Mods/web-issues#1360]
## Your username/username(s) affected
Vyxenne

## Bug/error being reported:
Notifications of posts to "Tracked" (followed) mods are not showing up OR being emailed

I am following several SSE mods, including Ecotone Dual Sheath, 360 Movement Behavior, Pretty Combat Animations, SkyUI, Smart Harvest SE, KS SMP Hair, Racemenu, BodySlide and Outfit Studio and several others. All of the mods I just named have received new comments since I last visited them. I have received ZERO notifications in my Forum Notifications section (much less the required emails) on ANY of those mods. **The only notifications I am receiving are for mods I manage.**

I recently submitted a bug report on this, faithfully filling out all of the steps even though they all said the same thing, and in fact the essence of the entire report was contained in the Title.

Yesterday, I received an email notice that my previous Bug Report had been closed: "fixed." I do not know who closed it or why they falsified a spurious claim of "fixed," but they are dead wrong- IT IS NOT FIXED! Please, what is the point in ignoring a valid bug report for 2-3 weeks then abruptly falsifying the status of the underlying issue and closing the Bug Report without even contacting the one who submitted the report to see if it was working for her?

Please, fix Notifications. They worked marvelously until you good folks broke them on 3/22/2021, a day which will go down in infamy in the annals of forum management. Please. Fix. Forum. Notifications.

**Comment by Vyxenne** [comment]
It seems that the forum cut my report off after the first section. Great. Should I submit a bug report on the Bug Reporting System?

**Comment by Pickysaurus** [comment]
Email notification are no something we have ever offered for site-based notifications (i.e. mod tracking) so it is correct you are no receiving them. If you're having a problem with tracked forum threads that could be a separate issue. 

In many cases where this has been reported the user has "Comments on files I'm tracking" turned off in their preferences, so it's likely to be a misconfigured setting rather than a bug. 

If you're still having the problem, feel free to PM me on the site with an example and I'll see what I can find out.
