### ISSUE TITLE
Cannot slow download on safari

### ISSUE THREAD

**Issue by JaneDoe-ctrl** [Nexus-Mods/web-issues#1498]
URL: https://www.nexusmods.com/stardewvalley/mods/1063?tab=description
Username on the Nexus: AwkwardGarbage
Bug/error being reported: Unable to click "slow download" on safari, has been happening for the past week
Steps to reproduce:
1. Open the provided link in safari
2. Select manual download and choose the "slow download" type
3. Optional: Right click "slow download" and inspect element: there will be an error of "#ERROR-download-location-not-found"

Expected result:
Immediate slow download of mod

Actual result:
Nothing happens

Link to the affected mod/image (if relevant):
![image](https://user-images.githubusercontent.com/49574498/159077387-427256c0-ecf4-4563-9a8a-e1c62564b5e5.png)

Notes: No add-ons or extensions installed on safari. Restarted the computer and browser several times along with logging in and out of nexus mods account, no change. Link works on Firefox though.

**Comment by Pickysaurus** [comment]
The error you pointed out is just leftover code and would not cause any issue. The problem is somewhere in your setup. Likely you're blocking JavaScript (either entirely or selectively). Or you're pressing the Vortex download option without having Vortex installed (I know you said manual but it's a common mistake!).

In summary it's either a local problem on your PC, some kind of network problem or just a mistake on your part.
