### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by Ewdle** [Nexus-Mods/web-issues#1503]
## Your username/username(s) affected
 ewadpierce

## Bug/error being reported:
 When i try to login it takes me to the login page and i put in my login info that it says I dont have permmision to access "users.nexusmods.com" even though Im just trying to login

**Comment by Ewdle** [comment]
Expected result: To login normally
Actual result: blocks me from logging in

**Comment by DoctorDrull** [comment]
Hi Im having this exact same problem. Check your email, i recieved an email asking me to reactivate my account and doing that seems to have fixed my problem.

**Comment by Pickysaurus** [comment]
This is a temporary issue as we've had to increase our security. Our team are aware but as it's the weekend I can't give any estimate on how long this will last.

**Comment by yorisama** [comment]
So why is this closed then - if you can't even try to fix it until Monday?  The system automatically brings us to open tickets - so we can make sure we aren't duplicating one - but YOU CLOSED THIS TICKET - WITHOUT FIXING IT!  so now there are duplicates that you are closing because there are duplicates.  

Your login page isn't working.
That should be an "all hands on deck" issue - you can't get $$ if no one can log in.

Or at least leave the ticket open so we know you are (will) work on it.
