### ISSUE TITLE
Can't change profile picture

### ISSUE THREAD

**Issue by DCOnline40** [Nexus-Mods/web-issues#1543]
DCOnline40

While trying to change my profile picture, it appears to upload the picture I want. However, the 'Done' button never lights up, nor does it work when I press it. The picture works on the forum and Vortex, just not on the main site. 

Not sure how to reproduce this

### Example:
1. Step 1
2. Step 2
3. Step 3
-->

## Expected result:
The picture would change

## Actual result:
Nothing happened, the picture did not change

**Comment by Pickysaurus** [comment]
DCOnline40 is not a username for an account on the site. 

I cannot replicate this. If the "Done" button doesn't light up, there's a high chance that the problem is caused by browser addons or privacy settings breaking the page. 

See this article for help: https://help.nexusmods.com/article/113-troubleshooting-website-issues
