### ISSUE TITLE
New Recently/Recent Activity missing icons for activity type

### ISSUE THREAD

**Issue by mjgreene** [Nexus-Mods/web-issues#177]
The new layout for 'Recent Activity' https://rd.nexusmods.com/skyrim/mods/newrecently is missing the icons that the old layout showed which indicated what the activity was (file upload, image, etc.) This is **_really_** important (to me, at least) because this is how I primarily track what happens on the site on a regular basis.

I sincerely hope you intend to restore these icons before sunsetting/retiring the old layout.  Thanks.

**Comment by verenion** [comment]
We don't plan on adding these back to the Recent Activity page. They were removed to streamline the page a little. We will investigate to see if there is value adding them back in.

**Comment by mrmason** [comment]
We've slightly changed this page to only list new mods and mods that have recently had the files updated.

If there is enough demand for seeing what mods have new images or descriptions changed then we can discuss re-adding that feature.

**Comment by DavidJCobb** [comment]
What would be the best way to show "demand?" Just commenting here? Or are you able to see who "subscribes" to an issue?

Being able to tell description changes from file changes is pretty helpful in general, and it addresses the way that some authors manually cross-link their descriptions together and bump *all of their old files* onto New Recently whenever they publish something new. Twenty similarly-named files in a row with just description updates are stale content and can be easily ignored. The other icons are also helpful -- being able to tell added videos from added files, for example.

**Comment by Thallassa** [comment]
Are the mods listed here only listed if files have changed, then? 

Because if they are being listed if anything has changed (images, description, or files), then yes, I do demand that the icons be restored. I only care about mods that have had files changed :P

**Comment by Dragon-32** [comment]
What DavidJCobb and Thallassa said.

**Comment by rscottexe** [comment]
Yes, that is what Tom is saying.

We've now got two dates/times for "Last Updated".

The first is the original last updated mechanic -- any time the mod author does anything with their file page it will update this timestamp.

The second is a new one which only tracks when the author has uploaded a new file to their file page.

The "new today/recently" page is now only tracking via that second timestamp, and not the original first. As such, any file you see in new today or new recently will have had a new file uploaded to it.

Similarly, if you search via "Last Updated" on RD, it will also be using that second timestamp.

This is to stop people deliberately "bumping" their files using simple description edits on purpose. If mod authors deliberately reload the same files every day to bump in this same manner we'll likely step in and moderate it, because that would be dickish.
