### ISSUE TITLE
Enhancement: I want to suggest

### ISSUE THREAD

**Issue by vanja-san** [Nexus-Mods/web-issues#182]
Maybe yes, maybe not.
**It:**
![Screenshot 1](https://user-images.githubusercontent.com/7201687/31949077-a360e5a8-b902-11e7-859e-1501a580364a.png)
**In it:** (It's just that your line is very empty.)
![Screenshot 2](https://user-images.githubusercontent.com/7201687/31949078-a3882d2a-b902-11e7-8eea-5a21c0da4866.png)

**Comment by krisser143** [comment]
I do personally think that the breadcrumb line fits perfectly fine above the text because it blends in well.

**Comment by vanja-san** [comment]
I agree, but... 
for example, the button "comment" is not needed, the user reads the article and gets to the page of comments, or the buttons for turning the news, also not very conveniently made. Even let the path be above the text, but the buttons need to be rearranged. Although, all users are comfortable in different ways.
Sorry for my English. (GTranslate helped me)

**Comment by vanja-san** [comment]
Although no, the "Comment" button is still useful, I'm just not one of those who often writes comments. But the paging buttons should be moved.

**Comment by krisser143** [comment]
I agree with the comment button, it should definitely be at the comments, because it's useless anyways and takes space. The buttons to switch news are a bit weird the way you draw them. Normally you would use such buttons you drew if it's a front page banner only with a title, but because the whole page is an article, the top part is more of an image rather than a banner.
And yes, you could even remove the arrows, nobody switches through the articles like that, they just read what they want from the front page.
