### ISSUE TITLE
Enhancement: Show tooltip of untruncated number when hovering above mod stats

### ISSUE THREAD

**Issue by Fhaarkas** [Nexus-Mods/web-issues#199]
Show a tooltip (or similarly unintrusive methods) showing untruncated number of mod stats when hovering above it with mouse cursor.

Just a suggestion out of preference, I suppose. I like those raw numbers and I loved checking in every hour/day or so to see the numbers trickle (this is starting to sound unhealthily obsessive), but that's not possible anymore with the new format.

Here's a rough mockup I made -
![mockup](https://user-images.githubusercontent.com/10703185/31970613-2c1140f8-b94b-11e7-92f7-9966433214ca.jpg)

**Comment by mrmason** [comment]
We've already been discussing this internally. The old site shows the fill numbers on the mod page - and at the moment we're leaning towards restoring that rather than having the shortened numbers. 

A hover over was suggested, but consensus seems to be that just showing the full number would be better.

**Comment by Fhaarkas** [comment]
That's great to hear!

**Comment by verenion** [comment]
We've already changed to using the full values now, so this must have been missed
