### ISSUE TITLE
VIEW NEW LAYOUT  

### ISSUE THREAD

**Issue by DonQuixoteIII** [Nexus-Mods/web-issues#222]
Let's say that I am seeing this prompt at the top of a mod page - one that I want to see.  So I click on it only to be thrown back to the top-level lite.  Not making any friends with that one...

**Comment by mrmason** [comment]
We're aware of this - the problem is that a number of pages have different URLS and some of the parameters don't quite match up.

This means that if we created dynamic linking - quite a lot of pages would immediately land on an error page - which is even worse. 

This message is only temporary until the site goes live.

If you want to see the equivalent page - just change `www` to `rd` in the URL and it will take you there. Sorry for the inconvenience!
