### ISSUE TITLE
Icon choice for Mod Status is reverse of all former UI standards

### ISSUE THREAD

**Issue by cdcooley** [Nexus-Mods/web-issues#246]
Bug/error being reported: 
Icon choice for Mod Status is reverse of all former UI standards. 
Steps to reproduce: This is about the Visible/Hidden radio buttons on the mod management page.
Expected result: The active option should be the one that appears highlighted.
Actual result: The filled white circle is indicating the inactive option and the circle with a center the color of the page background is the active option. Either those need to be reversed or some other color (like the blue theme color) needs to be inserted in the center of the active option.

**Comment by Fhaarkas** [comment]
I'm still having trouble understanding this issue since the radio buttons are not confusing to me at all. The fill is sufficiently spaced from the edge as to not have the white part outside it appear like a line. Not to mention the other circle doesn't have any fill at all so it can't possibly be the active choice.
![004](https://user-images.githubusercontent.com/10703185/32130941-fcb6484e-bbd4-11e7-82ae-1b4e9e1c1427.PNG)

That said the choice of white-base radio button does seem at odd with the mod page editor where dark-theme radio buttons are used. My proposal is to switch the button to a dark one, which would bring some consistency to radio button appearance. The downside is it will be inconsistent with the rest of user input controls (text field, dropdown menu etc) which all use light background. 
![bug_radio](https://user-images.githubusercontent.com/10703185/32131075-d954a852-bbd7-11e7-81d2-270f76d8e05c.png)  
Complimentary mockup

Or maybe nothing has to be done. ¯\\_(ツ)_/¯ (just kidding)
I do think there's been enough complaint about this little issue that maybe it warrants some attention.

**Comment by cdcooley** [comment]
Fhaarkas,
You talk about fill and edge but making that outer circle thicker or thinner as you show in those last two images makes absolutely no difference when I look at them because the core issue is that the inactive button is the most eye-catching variant. 

If there were multiple choices it would be possible to notice that the one that's different is the hollow circle but when there are just the two my instinct after looking at many different user interfaces for the past 40 years says that the boldest one that's filled in is the one that's selected. Calling the background color a fill seems absolutely backwards.

In my mind the best option would be to fill the active button with the site highlight color. If my choice is a solid white and a white ring around a blue circle my brain will be able to adapt to the idea that the blue one is the active one. But when the fill for the "active" button is the background color my mind rebels.

This isn't the only place on the site with those strange choices but it's the one that bothers me most because when I go to my mod management page it always looks like all my mods have been set to hidden. I've tried to adapt but it's been weeks now and I simply can't.

**Comment by Saavaas** [comment]
The bullets could be a browser/OS thing because mine looks different and has the more highlighted look. 
I'm on Firefox/win7 btw

![screenshot-2017-10-28 my nexus account at nexus mods and community](https://user-images.githubusercontent.com/33143907/32131676-f40cb30a-bb79-11e7-9e28-472694ff69fb.png)

**Comment by cdcooley** [comment]
So it looks like my real problem is the Windows 10 flattening of every UI element combined with something that's killing the color that should be in the center.

**Comment by Fhaarkas** [comment]
We can chalk it up to different conditioning I suppose. It's an interesting difference to say the least. To me the 'background' color here would be white - my mind just automatically filters out whatever color there is outside of it, and my eyes would be drawn to whichever one has a 'fill' first (I'm still gonna call it fill!). 

I agree that the best way to fix this would be to just use accent color. Doesn't have to strictly follow site accent, just have one distinct color for each spectrum (red for red shades, yellow for yellow shades etc). For sites with grey accent (if there's any), you can just use the generic Nexus yellow instead.  

![test_radio](https://user-images.githubusercontent.com/10703185/32133004-764f921a-bc01-11e7-87d3-07a8c034b8e5.PNG)
Because I love doing mockups

**Comment by Saavaas** [comment]
If they wanted to get really fancy, a switch for the on/off instances would work well too.
http://www.cssreflex.com/wp-content/uploads/2014/09/ui-switch.gif

**Comment by Zur13** [comment]
I'd like to add that the site have already uses 2 radio button variants one of which is the "good" and one is "bad" 
![nexusbullets](https://user-images.githubusercontent.com/33193255/32174261-111096b2-bd8a-11e7-9da1-0bb52632fbd9.PNG)
