### ISSUE TITLE
Sorting filters not being remembered across searches

### ISSUE THREAD

**Issue by solonlost** [Nexus-Mods/web-issues#280]
Bug/error being reported: Selected sorting filters not being remembered across searches.
Steps to reproduce: Do a search, set it to sort by "endorsements", then do another search, it will jump back to "Most recent" sorting.
Expected result: Like the old version of the site I would expect it to remember my sorting preferences
Actual result: Always jumps back to "Most recent" sorting.

**Comment by mrmason** [comment]
Hey - I have a feeling this might be because you're using the global search which is new functionality ( the search bar at the top of every page ).

If you do a search, and then you use the search filters on the page then it will keep your filter preferences - if you go a new global search then it will reset everything.

If I've got that wrong then please let me know and provide a screenshot of what you're doing.

**Comment by solonlost** [comment]
When I set the sort dropdown to endorsements, that functions as expected. If I then click on the lower link to the same area, the sort box jumps back to most recent. If it's intended behaviour, it should probably be re-evaluated.

![full-4657-79330-image](https://user-images.githubusercontent.com/19389518/32190732-0b385282-bdaf-11e7-9598-b81c9543d886.jpg)
