### ISSUE TITLE
Unique download numbers don't sum correctly

### ISSUE THREAD

**Issue by PoorlyAged** [Nexus-Mods/web-issues#315]
Bug/error being reported:

Unique download numbers do not sum correctly
- In heading shows 468 unique downloads
- V2 file shows 368 unique downloads
- Original file shows 125 unique downloads

Steps to reproduce:

https://rd.nexusmods.com/fallout4/mods/24909?tab=files and open both files 

Expected result:
the sum in the header should be 493 (368 + 125)

Actual result:
The sum is the header is 468

**Comment by verenion** [comment]
This is actually the intended mechanics. It matches the same values on the old site.  See : https://www.nexusmods.com/fallout4/mods/24909?tab=files. 

This is because the Unique Downloads for the mod, isn't a sum of all the file downloads, but a count of the unique people that have downloaded that mod.
