### ISSUE TITLE
Dedicated author action log is missing

### ISSUE THREAD

**Issue by Fhaarkas** [Nexus-Mods/web-issues#358]
On the old site there is a dedicated section for author action log, but it is not present in redesign.

Screenshot:
![screenshot 217](https://user-images.githubusercontent.com/10703185/32854077-7070de5a-ca78-11e7-9e99-31c4f7613669.PNG)
![screenshot 215](https://user-images.githubusercontent.com/10703185/32853813-775b5ad4-ca77-11e7-9bb1-d5056f6e8815.PNG)

**Comment by Rrrafau** [comment]
We do have the logs tab, you should be able to find it in the same section where description and files tabs are. If you cannot see it on a particular page can you please give us the url?

**Comment by Starfis** [comment]
I would say that the problem is that the log is usually overwhelmed with notices about people who endorsed the file while the notices about changes to the file by author is being shifted deep down.  At least that's how it looks like from my point of view as a mod user without access to any files. Maybe it would help to be able to filter endorsements from file updates, have separate logs just for them or at least be able to load the whole log at one click so we can at least use search function of a browser.

**Comment by Fhaarkas** [comment]
Right now, in 'Log' tab, there is a section for 'Mod Page Activity', which is the exact equivalent of the old 'Actions' tab. It does include author actions, however so does the old 'Actions' tab. The old site essentially list author actions twice - once in Actions tab along with user actions and once under Actions Log.  

I'm hesitating to suggest an improvement to the old system, since that would be considered as enhancement instead although that said, separating mod actions and author actions is the obvious solution for both old site redundancy and new site impracticality.  

My intention here to only report on the missing feature, as I've seen quite some feedback that erroneously assume Actions tab and Actions Log are now merged, when Actions tab (Mod Page Activity) is actually behaving exactly like it was, and it's just Actions Log that is missing.

**Comment by iamtiz** [comment]
Assigned #153597572

**Comment by iamtiz** [comment]
We added a dedicated action log control, just for the mod team actions
