### ISSUE TITLE
Drop down menus not working

### ISSUE THREAD

**Issue by Ironmind91** [Nexus-Mods/web-issues#427]
Hi team,

Drop down menus aren't working for me. The ones up the top of the page work but not the ones for images or selecting a category:

https://imgur.com/tUEbI3m
https://imgur.com/ZTLUQNg

**Comment by iamtiz** [comment]
Hi, is it only those 2 dropdowns that are not working for you? What browser version are you using?

**Comment by Ironmind91** [comment]
Any drop down menu that isn’t the main ones at the top of the page doesn’t work for me. I’m not sure how to check what version I’m using?

**Comment by SirSalami** [comment]
Can confirm, when trying to use the "add to favorites" drop-down associated with the game's list on the homepage. 

Examples:
Clicking on the 'plus' symbol expands menu properly: https://i.imgur.com/1fSngbD.png
Trying to hover over add to favorites option collapses the menu: https://i.imgur.com/xVUA3mT.png

**Comment by RFBomb** [comment]
Bumping this thread. Attempting to add a game to favorites does not work, instantly closes the menu. 
I have also tried the normal workarounds that allow functionality on sites like this, but those do not work either. 

(Those workarounds typically being right click to take focus away from the drop down via the OS instead of the browser the clicking on the desired item. Doing this takes focus away, the site detected that, and the menu closed immediately, never even giving the workaround a chance.)

**Comment by iamtiz** [comment]
Fixed

**Comment by Ironmind91** [comment]
This isn't fixed at all. Selecting a mod, then images and trying to change category shoes no drop down menu..
