### ISSUE TITLE
Can't click the 'View All Games' link on Nexus home page as element is beneath game link

### ISSUE THREAD

**Issue by Fironet** [Nexus-Mods/web-issues#464]
## Bug/error being reported:
When clicking on the `View All <number> Games` link it instead takes me to the game linked directly beneath (in the screenshot below that's Dark Souls). This wasn't an issue in the earlier version of the redesign.

While the page is loading the link works but following the remaining thumbnails/dark gradient overlay being loaded the element seems to be positioned beneath the game link.

Tested in Firefox, Opera.

![screen](https://i.imgur.com/W1gk6ly.png)

## Steps to reproduce:
1. Visit the rd.nexusmods.com.
2. Try clicking the `View All Games` link.

## Expected result:
The link would be clickable.

## Actual result:
It instead opens the link to the game directly beneath the desired click target.

**Comment by jmainz** [comment]
Can confirm that this is happening on Chrome 63.0.329.84 (Just use SemVer already Chrome!)

Tried messing with the DOM by recreating the element below the games-list div, but it still wasn't clickable there.

Side Note: From a UX perspective, I don't particularly like that setup because I don't expect it to take me to a new page, the block under a half-hidden list makes me think it should expand the list instead of navigate to the rest. Also, it just repeats the first page instead of continues my pagination, not good.

**Comment by iamtiz** [comment]
Fixed
