### ISSUE TITLE
"New version setup" window forces me to delete all mods.

### ISSUE THREAD

**Issue by Woulve** [Nexus-Mods/web-issues#486]
## Bug/error being reported:
Every once in a while (happened to me three times in 6 days now when I start nmm a window pops up telling me a new version is available and I HAVE to reinstall or completely uninstall all my mods to even be able to use nmm anymore, even though I have the lates version. I pressed "yes" to reinstall, but two times it just uninstalled all my mods and froze when reinstalling them, so I had to completely reinstall skyrim too and start enabling my mods all over again, which takes around 20 hours for me. There is no way to just dismiss the window, and I even have the latest version.

## Steps to reproduce:
Randomly when starting NMM

## Expected result:
I expect to not have to reinstall 250+ mods and skyrim every three days.

## Actual result:
I had to reinstall 250+ mods and skyrim every three days

**Comment by ousnius** [comment]
This is an NMM issue, not one with the website (you're on the wrong GitHub page). That said, they once implemented this for upgrading from an older version of NMM to a new one that required all mods to be installed. But this shouldn't be happening if you have the latest version of NMM.

I assume it's a bug with the registry or configuration files on your PC that somehow makes NMM think it should trigger that dialog again, but unfortunately I can't tell you how to fix it because I don't know.
