### ISSUE TITLE
Changelog Enhancements

### ISSUE THREAD

**Issue by fireundubh** [Nexus-Mods/web-issues#618]
**Inline editing of changelog entries:** There's no way to edit changelog entries at all right now. You have to delete an entry and then append a new entry to change the text of an entry. You should be able to click an entry to just start editing that entry. No popup. Honestly, if you do inline editing for changelogs, you should add inline editing everywhere. Why so many separate pages and popups?

**Reordering of changelog entries:** Entries are appended to the list by default, but what if you want an entry you added to be at the top of the version record? You have to delete _all_ the entries for that record, append the entry you want at the top, and then append each entry you just deleted. But, wait, what if after you're finished, you want another entry to be right under the top entry? Rinse. Repeat. In a perfect world, you'd have all the entries possible layed out the way you want them ahead of time, but this isn't a perfect world. You should be able to reorder entries by clicking up/down arrows or dragging a handle.

**Adding multiple version records simultaneously:** Sometimes you keep track of version changes in a post and then you decide to dump all those entries into the changelog. Unfortunately, you have to add each version record, one entry at a time, to do that.

**Large text box method should be parsed into separate text fields:** When you add entries with the large text box method, those entries should be added as separate text fields, line by line.

**Comment by iamtiz** [comment]
Assigned #161681375

**Comment by iamtiz** [comment]
Done

**Comment by fireundubh** [comment]
Awesome! 👍 👍 👍 

@iamtiz The new enhancement has a CSS issue, however. Looks like this issue affects only long log entries that wrap.

![2018-11-15 05_19_14](https://user-images.githubusercontent.com/1261664/48555441-1af80380-e896-11e8-944f-3528a0bc73d5.png)

**Comment by pStyl3** [comment]
I think that the overall changes are a great improvement, however I see an issue with the 4th feature request, namely ``Large text box method should be parsed into separate text fields:``.

For me, this results in a changelog, that get's a bit hard to look at. Please take a look at the changelog for [LOOT](https://www.nexusmods.com/skyrimspecialedition/mods/1918).

https://abload.de/img/examplefgdg9.png

Since the changelog I work with has the following structure
```
Added
- a
- b

Fixed
- c
- d
```
the large text box option was pretty good for my usecase.

If each row has it's own ``>``, then it becomes quite hard to look at:
```
> Added
> - a
> - b
> Fixed
> - c
> - d
```
You could of course argue, that I could remove the ``-`` on each of my individual rowes, but that makes it better to read against my different headers (Added/Fixed/Changed/et cetera) within the changelog.

As such, I would ask if it would be possible, so that the displayed outcome would be close to how it was before, possibly without a ``>`` for each row, if the large text box option was used.

**Comment by fireundubh** [comment]
@pStyl3 You could just prefix each entry. Like: https://www.nexusmods.com/pathfinderkingmaker/mods/32?tab=logs

**Comment by pStyl3** [comment]
So your proposal is:
```
> [Added] a
> [Added] b
> [Fixed] c
> [Fixed] d
```

This approach does work generally speaking. It's better than
```
> Added
> - a
> - b
> Fixed
> - c
> - d
```
though I would say, that
```
Added
- a
- b

Fixed
- c
- d
```
is still the best variant of the three, because visually it's the clearest, in my opinion.

Currently the entire LOOT changelog (LOOT 0.5.0 - LOOT 0.13.6) counts around 400 individual entries/rows. Because of that, and that before the change I think it was working pretty well for LOOT's case, I still think that adjusting the visual user side in order to mimic the Large text box option would be best in order to be able to read it easily.

**Comment by fireundubh** [comment]
I'd rather see a limited-scope Markdown parser implemented so you can add subheadings _if you want_. I don't think you should be forced to use subheadings.

For example:

```
Log entry
Log entry
# Added
**Bold** log entry
_Italicized_ log entry
`Inline monospace` log entry
# Fixed
## GUI
Log entry
Log entry
## Plugins
Log entry
## Metadata
Log entry
```
