### ISSUE TITLE
Two types of notifications cannot be turned off

### ISSUE THREAD

**Issue by DiaborMagics2** [Nexus-Mods/web-issues#665]
## Bug/error being reported:
When I click the gear icon to go to settings and scroll down to notification settings, I see I have 'Show user comments on the files you track' set to 'no'. Yet, almost all of my updates (and I get way too many per day because of this) are of the types 'x commented on y' and 'y has z new comments'. 

I also have always been unable to find an option to disable comments on files I track, but to get a notification anyway, if a user replies to a comment of mine. When I go to several mod pages to help with issues or ask for help myself, I always have to remember which I have been to and check back for replies. 

The first issue is the most important, but the second one is a thing and is annoying too at any rate. That is pretty much a feature request though, I think, so I will not cover that one below.

## Steps to reproduce:
1. Sign in on the Nexus
2. Click the gear icon to go to settings
3. Scroll down until the second-last option 'Show user comments on the files you track'
4. Click 'no'
(just to be sure...)
5. See the option right above the previous one, 'Show user activity on the files you track'
6. Click 'no'
7. Wait until you get notification about files you are tracking or not

## Expected result:
I should not be getting any notifications of the aforementioned types.

## Actual result:
I am still getting notifications of the aforementioned types.

**Comment by iamtiz** [comment]
Hi, you need to change the options in the "Notifications" section of the preferences, in order to enable / disable certain types of notification. The 'Show user comments on the files you track' option is in the "Homepage feeds" section, which affects only the tracked content tab in the site homepage.

![screenshot-2018-5-3 my nexus account at nexus mods and community](https://user-images.githubusercontent.com/3407947/39578306-b991c3fa-4edb-11e8-8c44-3a0c4d03aba2.png)

**Comment by DiaborMagics2** [comment]
But, I did change those settings, but they are not working for me. That is why I made this topic. Unless I'm not getting what you are trying to say?

**Comment by DiaborMagics2** [comment]
never mind. I'm just blind. It got it and it works :S Sorry to bother you :(
