### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by tambry** [Nexus-Mods/web-issues#720]
## Bug/error being reported:
[The Nexus mods website](https://www.nexusmods.com/) can't be accessed using IPv6.

### Method A:
1. Have an IPv6-capable connection (test [here](http://ipv6-test.com/)).
2. `curl "https://www.nexusmods.com" -6`

### Method B:
1. Have an IPv6-capable connection (test [here](http://ipv6-test.com/)).
2. Disable IPv4 on your computer.
3. Try to access [the Nexus mods website](https://www.nexusmods.com/).

## Expected result:
The website can be accessed over IPv6.

## Actual result:
The website can't be loaded over IPv6.

## Solution
Since Nexus mods uses Cloudflare, [it's as easy as flipping a switch](https://www.cloudflare.com/ipv6/).

**Comment by MeerMusik** [comment]
I cant believe you still did not fix that. Since I got a new Modem in December 2019 (switching from IPV4 only to IPV6 Dual-Stack Lite) I have constant Problems when I try to download directly through the Website or through Vortex.

Also, checking for Mod Updates through Vortex, is leading to a Timeout for 9 out of 10 Mods all the time. Which Mods are getting a timeout sometimes slightly differs. But overall it is 100 Percent reproducible. Often, I get logged out and have to manually log in to Vortex.

I have tried all sorts of different IPV4 and IPV6 DNS. I also made sure that the IPV6 and IPV6 Server are on the same Network to.

My Network is working fine. Only the Nexus Server's (and the Qt Git Server's but this is another Story) seems to have some Problems with IPV6 or Dual-Stack (Lite).

Please finally fix that! Thank you! :)

Fresh PING from Windows CMD Shell  (it always looks like this):
``
C:\WINDOWS\system32>ping -n 50 files.nexus-cdn.com
Pinging files.nexus-cdn.com [185.152.65.129] with 32 bytes of data:
Reply from 185.152.65.129: bytes=32 time=25ms TTL=54
Reply from 185.152.65.129: bytes=32 time=20ms TTL=54
Reply from 185.152.65.129: bytes=32 time=42ms TTL=54
Reply from 185.152.65.129: bytes=32 time=105ms TTL=54
Reply from 185.152.65.129: bytes=32 time=27ms TTL=54
Reply from 185.152.65.129: bytes=32 time=22ms TTL=54
Reply from 185.152.65.129: bytes=32 time=25ms TTL=54
Reply from 185.152.65.129: bytes=32 time=19ms TTL=54
Request timed out.
Request timed out.
Reply from 185.152.65.129: bytes=32 time=24ms TTL=54
Reply from 185.152.65.129: bytes=32 time=47ms TTL=54
Reply from 185.152.65.129: bytes=32 time=21ms TTL=54
Reply from 185.152.65.129: bytes=32 time=26ms TTL=54
Request timed out.
Reply from 185.152.65.129: bytes=32 time=23ms TTL=54
Reply from 185.152.65.129: bytes=32 time=21ms TTL=54
Reply from 185.152.65.129: bytes=32 time=30ms TTL=54
Reply from 185.152.65.129: bytes=32 time=20ms TTL=54
Request timed out.
Reply from 185.152.65.129: bytes=32 time=22ms TTL=54
Reply from 185.152.65.129: bytes=32 time=20ms TTL=54
Reply from 185.152.65.129: bytes=32 time=42ms TTL=54
Reply from 185.152.65.129: bytes=32 time=33ms TTL=54
Reply from 185.152.65.129: bytes=32 time=20ms TTL=54
Reply from 185.152.65.129: bytes=32 time=19ms TTL=54
Request timed out.
Reply from 185.152.65.129: bytes=32 time=23ms TTL=54
Request timed out.
Reply from 185.152.65.129: bytes=32 time=26ms TTL=54
Reply from 185.152.65.129: bytes=32 time=20ms TTL=54
Reply from 185.152.65.129: bytes=32 time=20ms TTL=54
Request timed out.
Reply from 185.152.65.129: bytes=32 time=37ms TTL=54
Reply from 185.152.65.129: bytes=32 time=20ms TTL=54
Request timed out.
Reply from 185.152.65.129: bytes=32 time=21ms TTL=54
Request timed out.
Request timed out.
Reply from 185.152.65.129: bytes=32 time=32ms TTL=54
Reply from 185.152.65.129: bytes=32 time=28ms TTL=54
Reply from 185.152.65.129: bytes=32 time=20ms TTL=54
Request timed out.
Reply from 185.152.65.129: bytes=32 time=24ms TTL=54
Reply from 185.152.65.129: bytes=32 time=19ms TTL=54
Reply from 185.152.65.129: bytes=32 time=20ms TTL=54
Reply from 185.152.65.129: bytes=32 time=22ms TTL=54
Request timed out.
Reply from 185.152.65.129: bytes=32 time=20ms TTL=54
Reply from 185.152.65.129: bytes=32 time=18ms TTL=54

Ping statistics for 185.152.65.129:
    Packets: Sent = 50, Received = 38, Lost = 12 (24% loss),
Approximate round trip times in milli-seconds:
    Minimum = 18ms, Maximum = 105ms, Average = 26ms
``

**Comment by patchling** [comment]
Umm... Have you checked to see if this only happens on nexus? If this is happening on a lot of other sites the problem is probably on your end. If it only happens on nexus then the problem is most likely with them. If this regularly happens on some web sites but not others it is harder to figure out where the problem is.

I have had problems of this nature before. It looks like it is the website I am visiting is having problems, but when I visit other sites it shows up on them as well. With no reference (that I could find) to this issue being strictly nexus or most sites you visit it has me curious.

**Comment by tambry** [comment]
Why was this closed? This doesn't seem to have been resolved.

**Comment by Pickysaurus** [comment]
I've seen IPv6 addresses in the site activity logs from time to time so I believe it is now possible to access the site this way. If not, it may be a problem at CloudFlare's end.

**Comment by tambry** [comment]
IPv6 indeed can't really be disabled in Cloudflare and one can derive the IPv6 addresses for the site from the IPv4 ones. You seeing in them logs would indicate a bot or a fanatic IPv6 fan having done that and added entries to their `/etc/hosts` or such.  
You however [don't have them in DNS](https://www.whatsmydns.net/?utm_medium=redirect#AAAA/www.nexusmods.com) so it's really not enabled for the general public.
```
[root@tambre ~]# dig nexusmods.com A +short
172.67.15.252
104.22.2.55
104.22.3.55
[root@tambre ~]# dig nexusmods.com AAAA +short
[root@tambre ~]#
```
I think you'll simply need to follow [these steps](https://support.cloudflare.com/hc/en-us/articles/229666767-Understanding-and-configuring-Cloudflare-s-IPv6-support#h_2fa0b554-3fd2-44a3-9a77-ee116c31b8c3) for Cloudflare to start publishing the AAAA records. They seem to have removed the original documentation and the new ones seem quite scarce.

I'd love to get this fixed, so if you have any trouble feel free to shoot me an email and we can do a call or whatever. 🙂

**Comment by Pickysaurus** [comment]
I'll reopen this for our web team to review, but I'm not sure if it'll get looked at any time soon.

**Comment by mrmason** [comment]
Our legacy systems do not have support for IPv6 logging.

We have at time supported IPv6 connectivity to our services, and some do support it - but we don't have 100% coverage yet. We aren't tracking this as a bug anywhere, but everything new we build supports IPv6, so we hope one day to fully support ipv6 from top to bottom.
