### ISSUE TITLE
[Bug] Button Manage does not work properly

### ISSUE THREAD

**Issue by Patriot99** [Nexus-Mods/web-issues#925]
Hi,
I used to publish the same post once and the problem was resolved, but after the next update nexusmod.com page the problem returned again.
When I go to the page of my translation and I want to edit the translation by clicking the button, Manage shows all the options, but when I want to choose one option from the list, the whole list of options disappears and I have to click several times for the Manage button to show its options and then click the PPM on this button the list of options has not disappeared and then select all options while holding the LPM and when I find the options, I can click to open the edition of your translation. This is inconvenient and should be displayed normally, not disappear when you want to select options from the list.
Video:
https://vimeo.com/274652633
Password:
test1

**Comment by Pickysaurus** [comment]
Hi @Patriot99 

I believe the problem you are facing is because you have a very long mod title and no header image. It is something we need to address but in the mean time you have a couple of workarounds.

1. Add a header image to your mod page.
2. Resize your browser window to a smaller break point (the button moves to next to the vote button.'

We'll update this report when it's fixed. :)

**Comment by Pickysaurus** [comment]
This will be carried over into the new mod page design once it is complete.
