### ISSUE TITLE
My account has been split in two.

### ISSUE THREAD

**Issue by 33458895** [Nexus-Mods/web-issues#976]
So I decided to support the site by paying for lifetime membership, but instead of giving that membership to my own account it created a secondary account with the exact same details and gave it to that. So I can use my membership to get uncapped downloads on Vortex but it remembers nothing about me.
Can you merge my accounts back together please?

**Comment by Pickysaurus** [comment]
Hi there,

It is possible you accidentally created a new account while purchasing Premium. 

In order to fix this, can you please raise a support ticket from your primary account, including the payment reference for the secondary account:
https://forums.nexusmods.com/index.php?app=nexus&module=support&section=new
